### PR TITLE
Add include-path-params flag

### PR DESCRIPTION
**Pull request by Pentusha**
for #16

### CODE REVIEW

**Review by effoeffi — COMMENTED** [review]
Thanks for the contribution @Pentusha
The PR looks good. I just have a question about the README. We are adding functionality to the actions, but should we explain it in the action repo, like you did with "include path parameter", or link to a central place, such as oasdiff, and improve its documentation over time for all use cases?

**Comment by Pentusha** [comment]
@effoeffi I'm copy-pasted these blocks from documentation. 
As a user of this action I expecting something like a table with mapping from action's parameters to CLI arguments. It seems to me that this would be a convenient option eliminating naming discrepancies. It would also help to keep track and find missing arguments.
Different commands have different sets of arguments, so it may need several tables in this case.

| Action Input | CLI | Default |
|--------|--------|--------|
| fail-on-diff | --fail-on-diff | false |
| include-path-params | --include-path-params | false |

**Comment by effoeffi** [comment]
@Pentusha, I like your idea. Would you please add a table for each command (diff, changelog, and breaking)?

**Review by effoeffi — APPROVED** [review]

**Comment by effoeffi** [comment]
First, thanks @Pentusha for the contribution.

> fail-on-diff boolean argument for breaking action is mapped to the argument with value --fail-on WARN

Do you suggest to extract it?

I invite you to join our slack community:
https://join.slack.com/t/oasdiff/shared_invite/zt-252mliwp2-kkG4R4m1y_n0WIlZORBn2g

**Pull request merged**
